site_name: My Docs
site_url: https://example.com/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - meta

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/main.min.js


plugin:
  - macros


nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Test: test/index.md
 


